name: Build and Deploy React App to Hostinger

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v4

            # Setup Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22" # Use your preferred Node version
                  cache: "npm"

            # Install dependencies
            - name: Install dependencies
              run: npm ci

            # Build the React app
            - name: Build React app
              run: npm run build
              env:
                  CI: false # Prevents warnings from being treated as errors
                  VITE_RAG_CHAT_API_URL: ${{ secrets.VITE_RAG_CHAT_API_URL }}

            - name: Clean target directory
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      rm -rf /public_html/buildabot/*

            # Deploy to Hostinger via SSH
            - name: Deploy to Hostinger via SSH
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  port: ${{ secrets.SSH_PORT }}
                  source: "dist/*"
                  target: "/public_html/buildabot"
                  strip_components: 1

            # Send notification on success
            - name: Deployment Success
              if: success()
              run: echo "🚀 Deployment completed successfully!"

            # Send notification on failure (optional)
            - name: Deployment Failed
              if: failure()
              run: echo "❌ Deployment failed. Check the logs for details."
