name: Deploy to Hostinger

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build application
              run: npm run build

            - name: Debug and prepare deployment
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      echo "Current user: $(whoami)"
                      echo "Current directory: $(pwd)"
                      echo "Home directory contents:"
                      ls -la
                      echo "Checking public_html permissions:"
                      ls -la public_html/ || echo "public_html not found at root"

                      # Try relative path instead of absolute
                      rm -rf public_html/buildabot
                      mkdir -p public_html/buildabot
                      chmod 755 public_html/buildabot

                      echo "Directory created successfully"

            - name: Deploy files via SSH
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  port: ${{ secrets.SSH_PORT }}
                  source: "dist/*"
                  target: "public_html/buildabot/"
                  strip_components: 1

            - name: Deployment Success
              if: success()
              run: echo "✅ Deployment to Hostinger successful!"

            - name: Deployment Failed
              if: failure()
              run: echo "❌ Deployment failed. Check the logs above."
